### ISSUE TITLE
Tooltip callback not being called on chart update

### ISSUE THREAD

**Issue by akegan** [y-takey/chartjs-plugin-stacked100#15]
I'm running into a strange bug, where when the data changes for a chart I'm rendering with this plugin, the tooltip callback I'm using isn't being run. Unlike in https://github.com/y-takey/chartjs-plugin-stacked100/issues/10, the bars are redrawing, and the numbers in the tooltips are updating, they just aren't being formatted with the callback I've specified.

I've narrowed it down to this plugin because I have a parallel non-stacked chart using the same options that's not having this issue. 

I'm using react-chartjs-2  version 2.7.0 with Typescript. 

Thanks!

**Comment by y-takey** [comment]
Hi @akegan :)
Thanks for your report! hmm, That certainly is a strange bug. Could you provide example code that reproduce the bug?

**Comment by akegan** [comment]
Looks like the issue is that my tooltip label callback is being replaced by the default in the plugin in the [beforeInit function](https://github.com/y-takey/chartjs-plugin-stacked100/blob/master/src/index.js#L84). In some cases, our callback is working out because when rendering the chart the before/after datasets update are being called twice:
```
beforeInit
beforeDatasetsUpdate
afterDatasetsUpdate
beforeDatasetsUpdate
afterDatasetsUpdate
```

but when everything is not called twice, our callback is replaced with yours:
eg:
```
beforeInit
beforeDatasetsUpdate
afterDatasetsUpdate
```

Could this be solved by detecting if another tooltip callback is assigned before assigning the one from the plugin?

Here's our sample code: https://github.com/bayesimpact/encompass/blob/4250ab870afead47abcc8870c9aae21fca418980/frontend/src/components/CensusDataChart/CensusDataChart.tsx#L88

**Comment by y-takey** [comment]
Thanks for your feedback and a sample code 👍 

I've fixed this issue, and published new version(0.4.5) of the plugin.
You can pass plugin option like this `stacked100: { enable: true, replaceTooltipLabel: false }`. [full example(README)](https://github.com/y-takey/chartjs-plugin-stacked100#use-your-tooltip-label)

I wanted automatic detection another tooltip option, but i couldn't. because the default options is passed by chart.js core, so can't determine that specified by user or not.

Thanks!

**Comment by akegan** [comment]
passing in the extra option with 0.4.5 works for me! thanks!

**Comment by y-takey** [comment]
Thank you the quick response :)
